version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:

  npm-deploy:
    working_directory: ~/code
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/code/.npmrc

      - run:
          name: Build and Deploy NPM Package
          command:  |
            npm install .
            npm run prepare
            npm run deploy
# TODO: only with master branch

workflows:
  node-tests:
    jobs:
      - node/test
      - npm-deploy:
          requires: 
            - node/test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master

